nodeLinker: node-modules

packageExtensions:
  "@lwrjs/lwc-module-provider@*":
    dependencies:
      "@babel/core": "*"
  "@lwrjs/server@*":
    dependencies:
      iltorb: "^2.0.0"
      node-zopfli-es: "^1.0.3"
  lwr@*:
    dependencies:
      lwc: ">= 1.x <= 2.x"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
