nodeLinker: node-modules

packageExtensions:
  "@lwrjs/lwc-module-provider@*":
    dependencies:
      "@babel/core": "*"
  "@lwrjs/server@*":
    dependencies:
      iltorb: ^2.0.0
      node-zopfli-es: ^1.0.3
  lwr@*:
    dependencies:
      lwc: ">= 1.x <= 2.x"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
